### ISSUE TITLE
weeks 1-5 - Grading

### ISSUE THREAD

**Issue by satenikmnatsakanyan-aua** [slavstepanyan/ENGS115-2021-Vyacheslav_Stepanyan#1]
Summary +2
HW1 - missing
HW2 +
HW3 - missing
HW4 +
Quiz1 +4.5
------

Week 1-5 Total (19%): 8.55
Participation (3%): 0.55
HW 1-4 (10%): 5
Quiz1 (6%): 3.00

**Comment by slavstepanyan** [comment]
please add 0.5 point for the quiz that we've discussed during the class
Thank you

**Comment by satenikmnatsakanyan-aua** [comment]
It is already added

**Comment by slavstepanyan** [comment]
Issue closed
Thanks
